"""Export an optimized design to a lens-sequence (.seq) file.

The output is plain-text sequence commands, loaded with the `IN` command.
Surface data use radius (RDY) mode (the format default), matching the format of
sequence files written by optical design software.
"""
from __future__ import annotations

import math
from typing import List

from .design import Design


def _fmt(x: float) -> str:
    if x is None or not math.isfinite(x) or x == 0.0:
        return "0.0"
    return f"{x:.6f}"


def _glass(g: str) -> str:
    g = (g or "").strip()
    return g.upper() if g else ""


def seq_string(design: Design, epd: float, field_angle_deg: float,
               na_obj: float = 0.0, obj_height: float = 0.0,
               finite: bool = False, wavelengths=(656.3, 587.6, 486.1),
               reference=587.6, dim: str = "MM", title: str = None) -> str:
    """Render a Design as a .seq text block.

    `wavelengths` are written in the order given (they are numbered 1..n);
    `reference` selects which one REF points at - if it is not one of the
    listed wavelengths the central one is used.  `dim` is the DIM token for
    the requested system units.
    """
    lines: List[str] = []
    name = title if title else design.title
    lines.append(f"!  {name}")
    lines.append("!  Generated by OptiForge (local, on-premise).")
    lines.append("!  Load with:  IN <filename>")
    lines.append("")

    lines.append(f"TIT '{name}'")
    lines.append(f"DIM {dim}")
    lines.append("WL " + " ".join(f"{w:.1f}" for w in wavelengths))
    if reference in wavelengths:
        ref_idx = list(wavelengths).index(reference) + 1
    else:
        ref_idx = (len(wavelengths) + 1) // 2      # central wavelength
    lines.append(f"REF {ref_idx}")

    # aperture
    if finite and na_obj:
        lines.append(f"NAO {na_obj:.6f}")          # object-side numerical aperture
    elif epd:
        lines.append(f"EPD {epd:.6f}")
    else:
        fno = design.fno if design.fno else (design.efl / epd if epd else 0.0)
        lines.append(f"FNO {fno:.6f}")

    # field
    if finite:
        lines.append(f"YOB 0.0 {obj_height:.6f}")     # object height field
        lines.append(f"SO 0.0 {design.obj_dist if math.isfinite(design.obj_dist) else 1e13:.6f}")
    else:
        lines.append(f"YAN 0.0 {field_angle_deg:.6f}")
        lines.append("SO 0.0 1.0E+13")

    lines.append("")
    # surfaces
    n = len(design.radius) - 2     # real surfaces count (skip object + image)
    stop = design.stop
    for k in range(1, n + 1):      # real surfaces 1..n
        r = design.radius[k]
        t = design.thick[k]        # gap after surface k
        g = design.glass[k] if k < len(design.glass) else ""
        rdy = _fmt(r) if r != 0.0 else "0.0"
        parts = [f"S {rdy} {_fmt(t)}"]
        if g:
            parts.append(_glass(g))
        lines.append(" ".join(parts))
        if k == stop:
            lines.append("STO")    # make this surface the aperture stop
    lines.append("SI 0.0 0.0")
    lines.append("GO")
    return "\n".join(lines)


def write_seq(path: str, design: Design, **kwargs) -> str:
    """Write the .seq file and return the rendered text."""
    text = seq_string(design, **kwargs)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text + "\n")
    return text
